name: rec_rec_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  camera: ^0.11.0
  path_provider: ^2.1.3
  path: ^1.9.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.5
  file_picker: ^8.0.3
  google_generative_ai: ^0.4.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  image_picker: ^1.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/scan_btn_bg.jpg
    - assets/pick_image_btn_bg.jpg
    - assets/images/apple_login.png
    - assets/images/google_login.png
