// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfy5hF-nlfx5mH_RPlsZXsmdYR6W-_4C8',
    appId: '1:480994439158:web:d779c14b4e88bf4be761d7',
    messagingSenderId: '480994439158',
    projectId: 'recipe-41603',
    authDomain: 'recipe-41603.firebaseapp.com',
    storageBucket: 'recipe-41603.appspot.com',
    measurementId: 'G-7GC41BMD2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE6J8SZrwnkMDwgnLw3gdQyo9Od1YKd5Q',
    appId: '1:480994439158:android:5a9c42887c831b9ee761d7',
    messagingSenderId: '480994439158',
    projectId: 'recipe-41603',
    storageBucket: 'recipe-41603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-UJv2GumUAKi0peCw2CUEE5KYY-X4PY',
    appId: '1:480994439158:ios:08c3994a1b68802be761d7',
    messagingSenderId: '480994439158',
    projectId: 'recipe-41603',
    storageBucket: 'recipe-41603.appspot.com',
    iosBundleId: 'com.example.recRecApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-UJv2GumUAKi0peCw2CUEE5KYY-X4PY',
    appId: '1:480994439158:ios:08c3994a1b68802be761d7',
    messagingSenderId: '480994439158',
    projectId: 'recipe-41603',
    storageBucket: 'recipe-41603.appspot.com',
    iosBundleId: 'com.example.recRecApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfy5hF-nlfx5mH_RPlsZXsmdYR6W-_4C8',
    appId: '1:480994439158:web:f575277eb19a38f3e761d7',
    messagingSenderId: '480994439158',
    projectId: 'recipe-41603',
    authDomain: 'recipe-41603.firebaseapp.com',
    storageBucket: 'recipe-41603.appspot.com',
    measurementId: 'G-B3DNN6L2VB',
  );

}